# Generated by Django 6.0.6 on 2026-06-18 06:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeveloperProfile',
            new_name='Profile',
        ),
    ]
