# Generated by Django 6.0.6 on 2026-06-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_userskill_skill_alter_profile_skills_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AlterField(
            model_name='userskill',
            name='level',
            field=models.CharField(choices=[('begineer', 'begineer'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], default='begineer', max_length=20),
        ),
    ]
